
-------------------------------------------------------------------
-- Version 1.0 of NewsSight Database. 
-- This script should drop any  current database and repopulate 
-- the server with the proper tables.
-------------------------------------------------------------------

-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 18:52:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newssight
-- -----------------------------------------------------
-- Database Schema V1 for NewsSight 
DROP SCHEMA IF EXISTS `newssight` ;

-- -----------------------------------------------------
-- Schema newssight
--
-- Database Schema V1 for NewsSight 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newssight` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `newssight` ;

-- -----------------------------------------------------
-- Table `newssight`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(500) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`sources` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`sources` (
  `name_id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `url` VARCHAR(150) NOT NULL,
  `category` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `topSortByAvailable` TINYINT NOT NULL,
  `latestSortByAvailable` TINYINT NOT NULL,
  `popularSortByAvailable` TINYINT NOT NULL,
  PRIMARY KEY (`name_id`),
  UNIQUE INDEX `name_id_UNIQUE` (`name_id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`articles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`articles` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL,
  `descripton` VARCHAR(200) NULL,
  `url` VARCHAR(200) NULL,
  `urlToImage` VARCHAR(200) NULL,
  `publishedAt` DATETIME(6) NULL,
  `savedAt` DATETIME(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonEntityResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonEntityResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonEntityResults` (
  `articleId` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `target` VARCHAR(45) NULL,
  `sentimentScore` FLOAT NULL,
  `sentimentLabel` VARCHAR(45) NULL,
  `sentimentLabelPositive` TINYINT NULL,
  `sentimentLabelNegative` TINYINT NULL,
  `sentimentLabelNeutral` TINYINT NULL,
  `emotionSadness` FLOAT NULL,
  `emotionJoy` FLOAT NULL,
  `emotionFear` FLOAT NULL,
  `emotionDisgust` FLOAT NULL,
  `eotionAnger` FLOAT NULL,
  `relevance` FLOAT NULL,
  `disambiguationSubtype` VARCHAR(300) NULL,
  `disambiguationName` VARCHAR(45) NULL,
  `disambiguationDBPediaResource` VARCHAR(300) NULL,
  `appearanceCount` INT NULL,
  PRIMARY KEY (`articleId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonConceptResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonConceptResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonConceptResults` (
  `articleId` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `relevance` FLOAT NULL,
  `DBPediaResource` VARCHAR(300) NULL,
  PRIMARY KEY (`articleId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonKeywordResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonKeywordResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonKeywordResults` (
  `articleId` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `sentimentScore` FLOAT NULL,
  `sentimentLabelPositive` TINYINT NULL,
  `sentimentLabelNeutral` TINYINT NULL,
  `sentimentLabelNegative` TINYINT NULL,
  `relevance` FLOAT NULL,
  `eotionsSadness` FLOAT NULL,
  `emotionsJoy` FLOAT NULL,
  `emotionsFear` FLOAT NULL,
  `emotionsDisgust` FLOAT NULL,
  `emotionsAnger` FLOAT NULL,
  PRIMARY KEY (`articleId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonOverallSentimentResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonOverallSentimentResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonOverallSentimentResults` (
  `idArticle` INT NOT NULL,
  `score` FLOAT NULL,
  `labelPositive` TINYINT NULL,
  `labelNegative` TINYINT NULL,
  `labelNeutral` TINYINT NULL,
  PRIMARY KEY (`idArticle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonTargetedSentimentResponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonTargetedSentimentResponses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonTargetedSentimentResponses` (
  `articleId` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `score` FLOAT NULL,
  `labelPositive` TINYINT NULL,
  `labelNegative` TINYINT NULL,
  `labelNeutral` TINYINT NULL,
  PRIMARY KEY (`articleId`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
