-- MySQL Script generated by MySQL Workbench
-- Tue May  8 15:34:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newssight
-- -----------------------------------------------------
-- Database Schema V1 for NewsSight 
DROP SCHEMA IF EXISTS `newssight` ;

-- -----------------------------------------------------
-- Schema newssight
--
-- Database Schema V1 for NewsSight 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newssight` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `newssight` ;

-- -----------------------------------------------------
-- Table `newssight`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(500) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`sources` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`sources` (
  `id` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `url` VARCHAR(500) NOT NULL,
  `category` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `topSortByAvailable` TINYINT NOT NULL DEFAULT 0,
  `latestSortByAvailable` TINYINT NOT NULL DEFAULT 0,
  `popularSortByAvailable` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '							';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`articles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`articles` (
  `id` INT NOT NULL,
  `title` VARCHAR(1000) NULL,
  `author` VARCHAR(200) NULL,
  `sourceId` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NULL,
  `url` VARCHAR(1000) NULL,
  `urlToImage` VARCHAR(1000) NULL,
  `publishedAt` DATETIME NULL,
  `savedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `sourceFK_idx` (`sourceId` ASC),
  INDEX `publishedAt_idx` (`publishedAt` ASC),
  CONSTRAINT `sourceFK`
    FOREIGN KEY (`sourceId`)
    REFERENCES `newssight`.`sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`article_entities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`article_entities` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`article_entities` (
  `articleId` INT NOT NULL,
  `type` VARCHAR(100) NULL,
  `target` VARCHAR(100) NULL,
  `salience` FLOAT NULL,
  INDEX `target_idx` (`target` ASC),
  CONSTRAINT `article_FK_watsonEntityResults`
    FOREIGN KEY (`articleId`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`sessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `newssight`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `newssight`;
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'saurav', '$2a$10$K5bPB3qf3Xw/9.vvMg/owuL0v3OU/HaVGJmqEkElx4ANxpNfh3Q4q', 'Saurav', 'Kadavath', 'sauravkadavath@gmail.com');
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'albert', '$2a$10$AZy0Rrefmf0cJzFuO/fr0OHM2QhMA1bnt4E/mvJw1C6ZEBaaQZ.Eu', 'Albert', 'Einstein', 'aeinstein@gmail.com');
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'will', '$2a$10$JK1LMrK8oD6iOOMaWuopY.vQxiJ3t3xeR9QgyLGu6bOpBmRxVHfIO', 'Will', 'Smith', 'willsmith@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `newssight`.`sources`
-- -----------------------------------------------------
START TRANSACTION;
USE `newssight`;
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('abc-news', 'ABC News', 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.', 'http://abcnews.go.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('al-jazeera-english', 'Al Jazeera English', 'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.', 'http://www.aljazeera.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('ars-technica', 'Ars Technica', 'The PC enthusiast\'s resource. Power users and the tools they love, without computing religion.', 'http://arstechnica.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('associated-press', 'Associated Press', 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.', 'https://apnews.com/', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('axios', 'Axios', 'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.', 'https://www.axios.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('bleacher-report', 'Bleacher Report', 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!', 'http://www.bleacherreport.com', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('bloomberg', 'Bloomberg', 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.', 'http://www.bloomberg.com', 'business', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('breitbart-news', 'Breitbart News', 'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.', 'http://www.breitbart.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('business-insider', 'Business Insider', 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.', 'http://www.businessinsider.com', 'business', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('buzzfeed', 'Buzzfeed', 'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.', 'https://www.buzzfeed.com', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('cbs-news', 'CBS News', 'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.', 'http://www.cbsnews.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('cnbc', 'CNBC', 'Get latest business news on stock markets, financial & earnings on CNBC. View world markets streaming charts & video; check stock tickers and quotes.', 'http://www.cnbc.com', 'business', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('cnn', 'CNN', 'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN', 'http://us.cnn.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('cnn-es', 'CNN Spanish', 'Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.', 'http://cnnespanol.cnn.com/', 'general', 'us', 'es', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('crypto-coins-news', 'Crypto Coins News', 'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.', 'https://www.ccn.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('engadget', 'Engadget', 'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.', 'https://www.engadget.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('entertainment-weekly', 'Entertainment Weekly', 'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.', 'http://www.ew.com', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('espn', 'ESPN', 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.', 'http://espn.go.com', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('espn-cric-info', 'ESPN Cric Info', 'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.', 'http://www.espncricinfo.com/', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('fortune', 'Fortune', 'Fortune 500 Daily and Breaking Business News', 'http://fortune.com', 'business', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('fox-news', 'Fox News', 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.', 'http://www.foxnews.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('fox-sports', 'Fox Sports', 'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.', 'http://www.foxsports.com', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('google-news', 'Google News', 'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('hacker-news', 'Hacker News', 'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham\'s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as \"anything that gratifies one\'s intellectual curiosity\".', 'https://news.ycombinator.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('ign', 'IGN', 'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.', 'http://www.ign.com', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('mashable', 'Mashable', 'Mashable is a global, multi-platform media and entertainment company.', 'http://mashable.com', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('medical-news-today', 'Medical News Today', 'Medical news and health news headlines posted throughout the day, every day.', 'http://www.medicalnewstoday.com', 'health', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('msnbc', 'MSNBC', 'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.', 'http://www.msnbc.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('mtv-news', 'MTV News', 'The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It\'s pop culture on steroids.', 'http://www.mtv.com/news', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('national-geographic', 'National Geographic', 'Reporting our world daily: original nature and science news from National Geographic.', 'http://news.nationalgeographic.com', 'science', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('nbc-news', 'NBC News', 'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.', 'http://www.nbcnews.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('new-scientist', 'New Scientist', 'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.', 'https://www.newscientist.com/section/news', 'science', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('newsweek', 'Newsweek', 'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.', 'http://www.newsweek.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('new-york-magazine', 'New York Magazine', 'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.', 'http://nymag.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('next-big-future', 'Next Big Future', 'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.', 'https://www.nextbigfuture.com', 'science', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('nfl-news', 'NFL News', 'The official source for NFL news, schedules, stats, scores and more.', 'http://www.nfl.com/news', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('nhl-news', 'NHL News', 'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.', 'https://www.nhl.com/news', 'sports', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('politico', 'Politico', 'Political news about Congress, the White House, campaigns, lobbyists and issues.', 'https://www.politico.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('polygon', 'Polygon', 'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.', 'http://www.polygon.com', 'entertainment', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('recode', 'Recode', 'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.', 'http://www.recode.net', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('reddit-r-all', 'Reddit /r/all', 'Reddit is an entertainment, social news networking service, and news website. Reddit\'s registered community members can submit content, such as text posts or direct links.', 'https://www.reddit.com/r/all', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('reuters', 'Reuters', 'Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.', 'http://www.reuters.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('techcrunch', 'TechCrunch', 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.', 'https://techcrunch.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('techradar', 'TechRadar', 'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.', 'http://www.techradar.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-hill', 'The Hill', 'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.', 'http://thehill.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-huffington-post', 'The Huffington Post', 'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.', 'http://www.huffingtonpost.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-new-york-times', 'The New York Times', 'The New York Times: Find breaking news, multimedia, reviews & opinion on Washington, business, sports, movies, travel, books, jobs, education, real estate, cars & more at nytimes.com.', 'http://www.nytimes.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-next-web', 'The Next Web', 'The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.', 'http://thenextweb.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-verge', 'The Verge', 'The Verge covers the intersection of technology, science, art, and culture.', 'http://www.theverge.com', 'technology', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-wall-street-journal', 'The Wall Street Journal', 'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.', 'http://www.wsj.com', 'business', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('the-washington-post', 'The Washington Post', 'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.', 'https://www.washingtonpost.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('time', 'Time', 'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.', 'http://time.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('usa-today', 'USA Today', 'Get the latest national, international, and political news at USATODAY.com.', 'http://www.usatoday.com/news', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('vice-news', 'Vice News', 'Vice News is Vice Media, Inc.\'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of \"under - reported stories\".', 'https://news.vice.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('wired', 'Wired', 'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.', 'https://www.wired.com', 'technology', 'us', 'en', 0, 0, 0);

COMMIT;

