-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 14:35:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newssight
-- -----------------------------------------------------
-- Database Schema V1 for NewsSight 
DROP SCHEMA IF EXISTS `newssight` ;

-- -----------------------------------------------------
-- Schema newssight
--
-- Database Schema V1 for NewsSight 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newssight` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `newssight` ;

-- -----------------------------------------------------
-- Table `newssight`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(500) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`sources` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`sources` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `url` VARCHAR(500) NOT NULL,
  `category` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `topSortByAvailable` TINYINT NOT NULL,
  `latestSortByAvailable` TINYINT NOT NULL,
  `popularSortByAvailable` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '							';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`articles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`articles` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `sourceId` VARCHAR(45) NULL,
  `descripton` VARCHAR(200) NULL,
  `url` VARCHAR(200) NULL,
  `urlToImage` VARCHAR(200) NULL,
  `publishedAt` DATETIME(6) NULL,
  `savedAt` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  INDEX `sourceFK_idx` (`sourceId` ASC),
  INDEX `publishedAt_idx` (`publishedAt` ASC),
  CONSTRAINT `sourceFK`
    FOREIGN KEY (`sourceId`)
    REFERENCES `newssight`.`sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonEntityResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonEntityResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonEntityResults` (
  `articleId` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `target` VARCHAR(45) NULL,
  `sentimentScore` FLOAT NULL,
  `sentimentLabel` VARCHAR(45) NULL,
  `sentimentLabelPositive` TINYINT NULL,
  `sentimentLabelNegative` TINYINT NULL,
  `sentimentLabelNeutral` TINYINT NULL,
  `emotionSadness` FLOAT NULL,
  `emotionJoy` FLOAT NULL,
  `emotionFear` FLOAT NULL,
  `emotionDisgust` FLOAT NULL,
  `emotionAnger` FLOAT NULL,
  `relevance` FLOAT NULL,
  `disambiguationSubtype` VARCHAR(300) NULL,
  `disambiguationName` VARCHAR(45) NULL,
  `disambiguationDBPediaResource` VARCHAR(300) NULL,
  `appearanceCount` INT NULL,
  PRIMARY KEY (`articleId`),
  INDEX `target_idx` (`target` ASC),
  CONSTRAINT `article_FK_watsonEntityResults`
    FOREIGN KEY (`articleId`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonConceptResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonConceptResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonConceptResults` (
  `articleId` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `relevance` FLOAT NULL,
  `DBPediaResource` VARCHAR(300) NULL,
  PRIMARY KEY (`articleId`),
  INDEX `target_idx` (`target` ASC),
  CONSTRAINT `article_FK_watsonConceptResults`
    FOREIGN KEY (`articleId`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonKeywordResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonKeywordResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonKeywordResults` (
  `articleId` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `sentimentScore` FLOAT NULL,
  `sentimentLabelPositive` TINYINT NULL,
  `sentimentLabelNeutral` TINYINT NULL,
  `sentimentLabelNegative` TINYINT NULL,
  `relevance` FLOAT NULL,
  `eotionsSadness` FLOAT NULL,
  `emotionsJoy` FLOAT NULL,
  `emotionsFear` FLOAT NULL,
  `emotionsDisgust` FLOAT NULL,
  `emotionsAnger` FLOAT NULL,
  PRIMARY KEY (`articleId`),
  INDEX `target_idx` (`target` ASC),
  CONSTRAINT `article_FK_watsonKeywordResults`
    FOREIGN KEY (`articleId`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonOverallSentimentResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonOverallSentimentResults` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonOverallSentimentResults` (
  `idArticle` INT NOT NULL,
  `score` FLOAT NULL,
  `labelPositive` TINYINT NULL,
  `labelNegative` TINYINT NULL,
  `labelNeutral` TINYINT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `score_idx` (`score` ASC),
  CONSTRAINT `article_FK_watsonOverallSentimentResults`
    FOREIGN KEY (`idArticle`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newssight`.`watsonTargetedSentimentResponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newssight`.`watsonTargetedSentimentResponses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newssight`.`watsonTargetedSentimentResponses` (
  `articleId` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `score` FLOAT NULL,
  `labelPositive` TINYINT NULL,
  `labelNegative` TINYINT NULL,
  `labelNeutral` TINYINT NULL,
  PRIMARY KEY (`articleId`),
  INDEX `target_idx` (`target` ASC),
  CONSTRAINT `article_FK_watsonTargetedSentimentResponses`
    FOREIGN KEY (`articleId`)
    REFERENCES `newssight`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `newssight`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `newssight`;
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'saurav', '$2a$10$K5bPB3qf3Xw/9.vvMg/owuL0v3OU/HaVGJmqEkElx4ANxpNfh3Q4q', 'Saurav', 'Kadavath', 'sauravkadavath@gmail.com');
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'albert', '$2a$10$AZy0Rrefmf0cJzFuO/fr0OHM2QhMA1bnt4E/mvJw1C6ZEBaaQZ.Eu', 'Albert', 'Einstein', 'aeinstein@gmail.com');
INSERT INTO `newssight`.`users` (`id`, `username`, `password`, `first_name`, `last_name`, `email`) VALUES (DEFAULT, 'will', '$2a$10$JK1LMrK8oD6iOOMaWuopY.vQxiJ3t3xeR9QgyLGu6bOpBmRxVHfIO', 'Will', 'Smith', 'willsmith@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `newssight`.`sources`
-- -----------------------------------------------------
START TRANSACTION;
USE `newssight`;
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('abc-news', 'ABC News', 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.', 'http://abcnews.go.com', 'general', 'us', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('associated-press', 'Associated Press', 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.', 'https://apnews.com/', 'general', 'uus', 'en', 0, 0, 0);
INSERT INTO `newssight`.`sources` (`id`, `name`, `description`, `url`, `category`, `country`, `language`, `topSortByAvailable`, `latestSortByAvailable`, `popularSortByAvailable`) VALUES ('bloomberg', 'Bloomberg', 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.', 'http://www.bloomberg.com/', 'business', 'us', 'en', 0, 0, 0);

COMMIT;

